### ISSUE TITLE
How do I read this?

### ISSUE THREAD

**Issue by ccorcos** [SquareBracketAssociates/SqueakByExample-english#2]

**Comment by SelfRando** [comment]
Good question!
But since I am running on Linux and happen to have the necessary dependencies installed I was able to download the zip, extract it and then run 'make' from the command line which created the PDF I am attaching here.

[SBE.pdf](https://github.com/SquareBracketAssociates/SqueakByExample-english/files/1100491/SBE.pdf)

**Comment by ccorcos** [comment]
Sweet. thanks!
